#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom lifecycle deprecated
## usethis namespace: end
NULL

#' Radar site groupings
#'
#' A small data lookup containing radar survey sites that should be renamed
#' during the data cleaning process in [process_radar_data()].
#'
#' @name rs
#' @docType data
#' @keywords data
#' @format A dataframe with 15 rows and 2 variables:
#' \describe{
#'  \item{original_name}{Original site name as appears in the 'Name$' column in the raw ECCC-FLNR MAMU radar data.}
#'  \item{new_name}{New, cleaned site name. This cleaned name can then be used in later analyses to group radar sites that need to be consolidated.}
#' }
"rs"

#' Radar site survey - Catchment combinations
#'
#' A small lookup table containing all survey location names and the
#' feature id (`fid`) of the associated catchment polygon feature in the `all_catchments.gpkg`
#' geopackage file. This table is used to match survey data to the correct catchment.
#'
#' @name catch_combos
#' @docType data
#' @keywords data
#' @format A dataframe with 226 rows and 2 variables:
#' \describe{
#'  \item{new_name}{New, cleaned site name as generated by [process_radar_data()]. This cleaned name is associated with a shapefile feature id (`fid`) in the `all_catchments` geopackage.}
#'  \item{fid}{Feature ID of the associated catchment polygon feature within [all_catchments].}
#' }
"catch_combos"

#' All catchments
#'
#' A spatial feature (`sf`) class object containing a multipolygon
#' of all versions of all MAMU catchments as of 2023-03-31.
#'
#' @name all_catchments
#' @docType data
#' @keywords spatial feature, data
#' @format A spatial feature (`sf`) object containing 130 features
#' \describe{
#'  \item{fid}{Feature ID of the polygon. Primary key differentiating each unique polygon and used to match radar survey data to catchments.}
#'  \item{region}{MAMU conservation region the catchment falls within, as originally defined in FLNR polygons.}
#'  \item{region_2}{MAMU conservation region the catchment falls within, as defined by ECCC.}
#'  \item{code}{Short alphanumeric code abbreviating the catchment name.}
#'  \item{catchment}{Name of the catchment.}
#'  \item{version}{Version number of the catchment. Useful to keep track of cases where the catchment has multiple iterations and been re-drawn (e.g., see Artlish or Toquart for an example).}
#'  \item{coastal_buff_500m}{Logical (T/F) - does the catchment have a 500m buffer from the coastline?}
#'  \item{area}{Polygon area in m^2.}
#' }
"all_catchments"
